title: "Dev & Tech Blog"
author: "Ernest Paśnik"
remote_theme: "pages-themes/cayman@v0.2.0"
plugins:
  - jekyll-remote-theme

social-network-links:
  rss: true
  facebook: "ernest.pasnik"
  github: "ernestpasnik"
  youtube: "@Hajt2k"

rss-description: "Insights, tutorials, and trends in development and technology for devs and tech enthusiasts."

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false

keywords: "development, technology, coding, programming, tutorials"

date_format: "%B %-d, %Y"
timezone: "Europe/Warsaw"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5

kramdown:
  input: GFM
