title: "Dev & Tech Blog"
author: "Ernest Paśnik"

social-network-links:
  rss: true
  facebook: "ernest.pasnik"
  github: "ernestpasnik"
  youtube: "@Hajt2k"

rss-description: "Tutorials for devs and tech enthusiasts"

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false

keywords:" technology,coding,programming"

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

date_format: "%B %-d, %Y"
timezone: "Europe/Warsaw"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5

kramdown:
  input: GFM
